# Generated by Django 6.0.7 on 2026-08-26 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_alter_commande_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée')], default='en_attente', max_length=20)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_status', models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée')], max_length=20)),
                ('nouveau_status', models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_livraison', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='livraison.livraison')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
