# Generated by Django 6.0.8 on 2026-09-26 20:02

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='code_chiffre',
            field=apps.core.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livraison',
            name='code_essais',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livraison',
            name='code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_livraison_estimee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='tentatives',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livraisonhistorique',
            name='role_acteur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='livraisonhistorique',
            name='ancien_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='livraisonhistorique',
            name='nouveau_status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée'), ('annulee', 'Annulée')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContestationLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motif', models.TextField(max_length=1000)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('rejetee', 'Rejetée'), ('fondee', 'Fondée')], db_index=True, default='ouverte', max_length=10)),
                ('commentaire_resolution', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contestation', to='livraison.livraison')),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_livraison_resolues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
