# Generated by Django 6.0.8 on 2026-09-26 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# Tarifs initiaux PROVISOIRES (FCFA), à ajuster par l'équipe via l'API
# d'administration (/api/livraison/admin/tarifs/) : ce ne sont pas des
# valeurs de référence. Sans tarif par défaut, aucune commande possible (503).
TARIFS_INITIAUX = {"abidjan": 1500, "hors_abidjan": 3000}


def creer_tarifs_initiaux(apps, schema_editor):
    TarifLivraison = apps.get_model("livraison", "TarifLivraison")
    for zone, montant in TARIFS_INITIAUX.items():
        TarifLivraison.objects.get_or_create(zone=zone, commune_normalisee="", defaults={"montant": montant})


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_fiches_des_commandes_annulees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('abidjan', 'Abidjan'), ('hors_abidjan', 'Hors Abidjan')], max_length=20)),
                ('commune', models.CharField(blank=True, help_text='Vide : tarif par défaut de la zone.', max_length=100)),
                ('commune_normalisee', models.CharField(blank=True, editable=False, max_length=100)),
                ('montant', models.PositiveIntegerField(help_text='FCFA payés par le client pour une commande (un colis).')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs_livraison_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['zone', 'commune_normalisee'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'commune_normalisee'), name='tarif_livraison_unique_par_commune')],
            },
        ),
        migrations.RunPython(creer_tarifs_initiaux, migrations.RunPython.noop),
    ]
