# Generated by Django 6.0.8 on 2026-09-27 09:24

import unicodedata

from django.conf import settings
from django.db import migrations, models

# Communes du district autonome d'Abidjan : les dix de l'ancienne ville
# d'Abidjan, plus Anyama, Bingerville et Songon. Le serveur en déduit la zone
# « abidjan » d'une adresse ; toute autre commune est hors Abidjan. Liste
# administrable ensuite (/api/livraison/admin/tarifs/).
COMMUNES_DISTRICT_ABIDJAN = [
    "Abobo", "Adjamé", "Attécoubé", "Cocody", "Koumassi", "Marcory", "Plateau", "Port-Bouët",
    "Treichville", "Yopougon", "Anyama", "Bingerville", "Songon",
]


def normaliser_commune(commune):
    # Copie figée de apps.livraison.models.normaliser_commune.
    decompose = unicodedata.normalize("NFKD", (commune or "").casefold())
    return "".join(caractere for caractere in decompose if caractere.isalnum())


def creer_communes(apps, schema_editor):
    """Chaque commune au tarif par défaut d'Abidjan en vigueur (provisoire,
    comme lui) ; une commune qui a déjà un tarif est laissée telle quelle."""
    TarifLivraison = apps.get_model("livraison", "TarifLivraison")
    defaut = TarifLivraison.objects.filter(zone="abidjan", commune_normalisee="").first()
    montant = defaut.montant if defaut is not None else 1500
    for commune in COMMUNES_DISTRICT_ABIDJAN:
        TarifLivraison.objects.get_or_create(
            commune_normalisee=normaliser_commune(commune),
            defaults={"zone": "abidjan", "commune": commune, "montant": montant},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0004_tarifs_de_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tariflivraison',
            name='tarif_livraison_unique_par_commune',
        ),
        migrations.AddConstraint(
            model_name='tariflivraison',
            constraint=models.UniqueConstraint(condition=models.Q(('commune_normalisee', ''), _negated=True), fields=('commune_normalisee',), name='tarif_livraison_une_zone_par_commune'),
        ),
        migrations.AddConstraint(
            model_name='tariflivraison',
            constraint=models.UniqueConstraint(condition=models.Q(('commune_normalisee', '')), fields=('zone',), name='tarif_livraison_un_defaut_par_zone'),
        ),
        migrations.RunPython(creer_communes, migrations.RunPython.noop),
    ]
