# Generated by Django 6.0.7 on 2026-08-30 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_alter_commande_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fournisseur', models.CharField(db_index=True, max_length=50)),
                ('evenement_id', models.CharField(db_index=True, max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('statut_traitement', models.CharField(choices=[('traite', 'Traité'), ('ignore', 'Ignoré (Doublon)'), ('erreur', 'Erreur de traitement')], default='traite', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Journal Webhook',
                'verbose_name_plural': 'Journaux Webhooks',
                'ordering': ['-date_reception'],
                'constraints': [models.UniqueConstraint(fields=('fournisseur', 'evenement_id'), name='unique_webhook_fournisseur_evenement')],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('methode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('carte_bancaire', 'Carte Bancaire (Visa / Mastercard)'), ('espece_livraison', 'Paiement à la livraison (Cash on Delivery)')], default='wave', max_length=25)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], db_index=True, default='en_attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('transaction_id_externe', models.CharField(blank=True, db_index=True, help_text='Identifiant de transaction retourné par la passerelle de paiement', max_length=150, null=True)),
                ('url_paiement', models.URLField(blank=True, help_text='URL de paiement externe ou de redirection vers le checkout de la passerelle', max_length=500, null=True)),
                ('adresse_livraison', models.CharField(blank=True, default="Abidjan, Côte d'Ivoire", help_text='Adresse de livraison à transmettre au module de livraison', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données brutes retournées par la passerelle ou informations contextuelles')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='commandes.commande', verbose_name='Commande associée')),
                ('groupe_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='commandes.groupecommande', verbose_name='Groupe de commandes associé')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
