# Generated by Django 6.0.8 on 2026-09-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='adresse_livraison',
            field=models.CharField(blank=True, help_text='Adresse de livraison à transmettre au module de livraison', max_length=255),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé'), ('a_rembourser', 'À rembourser')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
