# Generated by Django 6.0.8 on 2026-09-26 18:00

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_frais_vendeur_figes'),
        ('paiements', '0002_statut_a_rembourser_sans_adresse_fictive'),
        ('retours', '0002_alter_photoretour_image'),
        ('vendeurs', '0004_boutique_nom_normalise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='commandes',
            field=models.ManyToManyField(blank=True, related_name='paiements_couvrants', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='fournisseur',
            # Paiements existants : tous ouverts par l'ancienne simulation.
            field=models.CharField(default='simule', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='hash_jeton_notification',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='journalwebhook',
            name='statut_traitement',
            field=models.CharField(choices=[('recu', 'Reçu'), ('traite', 'Traité'), ('ignore', 'Ignoré (transaction non finalisée)'), ('erreur', 'Erreur de traitement')], default='recu', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('carte_bancaire', 'Carte Bancaire (Visa / Mastercard)')], default='wave', max_length=25),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='transaction_id_externe',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='url_paiement',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Reversement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_frais_fixes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_retours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ajustements', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_a_verser', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente_livraison', 'En attente de livraison'), ('en_retractation', 'Délai de rétractation en cours'), ('suspendu', 'Suspendu (retour en cours)'), ('disponible', 'Disponible'), ('en_cours', 'Versement en cours'), ('verse', 'Versé'), ('annule', 'Annulé')], db_index=True, default='en_attente_livraison', max_length=25)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_disponibilite', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('mobile_money', 'Mobile money')], default='mobile_money', max_length=20)),
                ('numero_destinataire', apps.core.fields.EncryptedCharField(blank=True, default='')),
                ('operateur', models.CharField(blank=True, max_length=20)),
                ('fournisseur', models.CharField(blank=True, max_length=30)),
                ('reference_externe', models.CharField(blank=True, max_length=150)),
                ('hash_jeton_notification', models.CharField(blank=True, max_length=64)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversements', to='vendeurs.boutique')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversement', to='commandes.commande')),
                ('verse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AjustementVendeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Négatif, en FCFA.', max_digits=12)),
                ('motif', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements', to='vendeurs.boutique')),
                ('retour', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustement_vendeur', to='retours.demanderetour')),
                ('reversement_impute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_imputes', to='paiements.reversement')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BaremeFrais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('taux_commission', models.DecimalField(decimal_places=2, help_text='Commission en % du prix de vente (avant remise).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('frais_fixe_article', models.PositiveIntegerField(help_text='FCFA par article vendu.')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baremes_frais', to='vendeurs.boutique')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barème de frais',
                'verbose_name_plural': 'Barèmes de frais',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='bareme_frais_dates_coherentes'), models.CheckConstraint(condition=models.Q(('taux_commission__gte', 0), ('taux_commission__lte', 100)), name='bareme_frais_taux_entre_0_et_100')],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(choices=[('commande_annulee', 'Commande annulée après paiement'), ('paiement_en_double', 'Commande déjà payée par un autre paiement'), ('retour', 'Retour remboursé')], max_length=30)),
                ('statut', models.CharField(choices=[('a_traiter', 'À traiter'), ('effectue', 'Effectué'), ('refuse', 'Refusé')], db_index=True, default='a_traiter', max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=150)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='commandes.commande')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='paiements.paiement')),
                ('retour', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remboursement', to='retours.demanderetour')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('retour__isnull', True)), fields=('paiement', 'commande'), name='unique_remboursement_paiement_commande')],
            },
        ),
        migrations.AddIndex(
            model_name='reversement',
            index=models.Index(fields=['boutique', 'statut'], name='paiements_r_boutiqu_745c94_idx'),
        ),
        migrations.AddConstraint(
            model_name='ajustementvendeur',
            constraint=models.CheckConstraint(condition=models.Q(('montant__lt', 0)), name='ajustement_vendeur_negatif'),
        ),
    ]
