# Generated by Django 6.0.8 on 2026-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_reprise_des_donnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='motif',
            field=models.CharField(choices=[('commande_annulee', 'Commande annulée après paiement'), ('paiement_en_double', 'Commande déjà payée par un autre paiement'), ('retour', 'Retour remboursé'), ('livraison_non_recue', 'Livraison contestée (colis non reçu)')], max_length=30),
        ),
    ]
