# Generated by Django 6.0.8 on 2026-09-26 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_frais_de_livraison'),
        ('paiements', '0005_motif_livraison_non_recue'),
        ('retours', '0004_frais_livraison_rembourses'),
        ('vendeurs', '0005_livraison_offerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustementvendeur',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_vendeur', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='ajustementvendeur',
            name='nature',
            field=models.CharField(choices=[('retour', 'Retour remboursé après versement'), ('livraison_offerte', 'Livraison offerte (reste non couvert)'), ('frais_livraison_retour', 'Frais de livraison remboursés (retour)')], default='retour', max_length=30),
        ),
        migrations.AddField(
            model_name='reversement',
            name='montant_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='ajustementvendeur',
            constraint=models.UniqueConstraint(condition=models.Q(('nature', 'retour'), _negated=True), fields=('commande', 'nature'), name='ajustement_vendeur_unique_par_commande'),
        ),
    ]
