# Generated by Django 6.0.8 on 2026-09-28 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_livraison_offerte_et_ajustements'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremefrais',
            name='frais_fixe_petit_article',
            field=models.PositiveIntegerField(blank=True, help_text='FCFA par article dont le prix effectif ne dépasse pas seuil_petit_article, TVA incluse.', null=True),
        ),
        migrations.AddField(
            model_name='baremefrais',
            name='seuil_petit_article',
            field=models.PositiveIntegerField(blank=True, help_text="Prix effectif (FCFA) jusqu'auquel, inclus, un article paie frais_fixe_petit_article. Vide : un seul frais fixe.", null=True),
        ),
        migrations.AlterField(
            model_name='baremefrais',
            name='frais_fixe_article',
            field=models.PositiveIntegerField(help_text='FCFA par article vendu, TVA incluse.'),
        ),
        migrations.AlterField(
            model_name='baremefrais',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, help_text="Commission en % du prix effectif de l'article (promotion comprise, avant coupon), TVA incluse.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='baremefrais',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frais_fixe_petit_article__isnull', True), ('seuil_petit_article__isnull', True)), models.Q(('frais_fixe_petit_article__isnull', False), ('seuil_petit_article__isnull', False)), _connector='OR'), name='bareme_frais_petit_article_complet_ou_absent'),
        ),
    ]
