# Generated by Django 6.0.8 on 2026-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_bareme_plateforme_14_pourcent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_derniere_reconciliation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
