# Generated by Django 6.0.8 on 2026-09-13 15:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/categories/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.ImageField(upload_to='catalogue/produits/%Y/%m/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
    ]
