# Generated by Django 6.0.8 on 2026-09-25 22:52

from django.db import migrations, models
from django.db.models import F, Q


def verifier_les_donnees(apps, schema_editor):
    """Arrêt explicite si des données existantes violent les nouvelles règles
    de prix. Aucune correction automatique : fixer un prix est une décision
    du vendeur. Corriger les ids listés puis relancer `migrate`."""
    Produit = apps.get_model('catalogue', 'Produit')
    VarianteProduit = apps.get_model('catalogue', 'VarianteProduit')
    problemes = []
    controles = [
        ("produits à prix de base négatif", Produit.objects.filter(prix_base__lt=0)),
        ("variantes à prix nul ou négatif", VarianteProduit.objects.filter(prix__lte=0)),
        ("variantes à prix promo incohérent (≤ 0 ou ≥ prix)",
         VarianteProduit.objects.filter(prix_promo__isnull=False).filter(Q(prix_promo__lte=0) | Q(prix_promo__gte=F('prix')))),
        ("variantes à poids négatif", VarianteProduit.objects.filter(poids_kg__lt=0)),
    ]
    for libelle, queryset in controles:
        ids = list(queryset.values_list('id', flat=True))
        if ids:
            problemes.append(f"{libelle} : {ids}")
    if problemes:
        raise RuntimeError("Données catalogue à corriger avant migration :\n- " + "\n- ".join(problemes))


def attribuer_les_desactivations_existantes(apps, schema_editor):
    """Produits déjà inactifs : jusqu'ici seul le vendeur pouvait désactiver
    un produit par l'API (l'administration n'avait pas d'accès). Ils sont donc
    attribués au vendeur, qui garde la main dessus."""
    Produit = apps.get_model('catalogue', 'Produit')
    Produit.objects.filter(est_actif=False).update(desactive_par='vendeur')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_categorie_image_alter_imageproduit_image'),
        ('vendeurs', '0004_boutique_nom_normalise'),
    ]

    operations = [
        migrations.RunPython(verifier_les_donnees, migrations.RunPython.noop),
        migrations.AddField(
            model_name='produit',
            name='desactive_par',
            field=models.CharField(blank=True, choices=[('vendeur', 'Vendeur'), ('administration', 'Administration ANITCHE')], help_text="Qui a désactivé le produit (vide s'il est actif). Une désactivation de l'administration (modération) ne peut être levée que par elle.", max_length=20),
        ),
        migrations.RunPython(attribuer_les_desactivations_existantes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(('prix_base__gte', 0)), name='produit_prix_base_positif'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('desactive_par', ''), ('est_actif', True)), models.Q(('est_actif', False), models.Q(('desactive_par', ''), _negated=True)), _connector='OR'), name='produit_desactivation_coherente'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('prix__gt', 0)), name='variante_prix_strictement_positif'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('prix_promo__isnull', True), models.Q(('prix_promo__gt', 0), ('prix_promo__lt', models.F('prix'))), _connector='OR'), name='variante_prix_promo_coherent'),
        ),
        migrations.AddConstraint(
            model_name='varianteproduit',
            constraint=models.CheckConstraint(condition=models.Q(('poids_kg__isnull', True), ('poids_kg__gte', 0), _connector='OR'), name='variante_poids_positif'),
        ),
    ]
