# Generated by Django 6.0.8 on 2026-10-06 12:21

from django.db import migrations, models

# Corps de catalogue_produit_public (migration 0004), avec en option la
# miniature de la MÊME image que `image_principale` (même tri, même LIMIT).
# Colonnes et ordre inchangés : CREATE OR REPLACE VIEW n'accepte qu'un ajout
# en fin de liste, et il garde les droits déjà accordés au rôle en lecture
# seule de FastAPI (infra/postgres/fastapi_readonly.sql).
IMAGE = """(SELECT nullif(i.{colonne}, '') FROM catalogue_imageproduit i WHERE i.produit_id = p.id
            ORDER BY i.est_principale DESC, i.ordre, i.id LIMIT 1)"""

VUE = """
    {instruction} catalogue_produit_public AS
    SELECT p.id, p.nom, p.slug, p.prix_base, p.date_creation,
           p.categorie_id, c.nom AS categorie_nom, c.slug AS categorie_slug,
           c.parent_id AS categorie_parent_id, cp.slug AS categorie_parent_slug,
           p.boutique_id, b.nom AS boutique_nom, b.slug AS boutique_slug,
           offre.prix_min, offre.en_stock,
           {image_principale} AS image_principale,
           catalogue_normaliser(p.nom) AS nom_normalise,
           catalogue_normaliser(p.nom || ' ' || p.description) AS texte_normalise{miniature}
    FROM catalogue_produit p
    JOIN vendeurs_boutique b ON b.id = p.boutique_id
    JOIN utilisateurs_utilisateur u ON u.id = b.proprietaire_id
    LEFT JOIN catalogue_categorie c ON c.id = p.categorie_id
    LEFT JOIN catalogue_categorie cp ON cp.id = c.parent_id
    LEFT JOIN LATERAL (
        SELECT min(coalesce(v.prix_promo, v.prix)) AS prix_min,
               coalesce(bool_or(s.quantite_disponible > 0), false) AS en_stock
        FROM catalogue_varianteproduit v
        LEFT JOIN catalogue_stock s ON s.variante_id = v.id
        WHERE v.produit_id = p.id AND v.est_active
    ) offre ON true
    WHERE p.est_actif
      AND b.est_active AND NOT b.est_suspendue
      AND u.role = 'vendeur' AND u.statut_kyc = 'valide' AND u.is_active
      AND EXISTS (SELECT 1 FROM catalogue_varianteproduit v WHERE v.produit_id = p.id AND v.est_active)
"""

AVEC_MINIATURE = VUE.format(
    instruction="CREATE OR REPLACE VIEW",
    image_principale=IMAGE.format(colonne="image"),
    miniature=",\n           " + IMAGE.format(colonne="miniature") + " AS miniature_principale",
)

# Retour arrière : une colonne ne se retire pas par CREATE OR REPLACE. La vue
# est supprimée puis recréée telle que la migration 0004 l'a créée, ce qui
# retire les droits de FastAPI sur elle : relancer le script de droits.
SANS_MINIATURE = VUE.format(
    instruction="CREATE VIEW", image_principale=IMAGE.format(colonne="image"), miniature="",
)


def executer(*instructions):
    def operation(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        for instruction in instructions:
            schema_editor.execute(instruction)
    return operation


class Migration(migrations.Migration):
    """Miniatures des images produit : colonne `miniature` (nullable, ajout
    sans réécriture de table) et colonne `miniature_principale` en fin de la
    vue catalogue_produit_public lue par FastAPI. Les images existantes se
    remplissent avec `python manage.py generer_miniatures`."""

    dependencies = [
        ('catalogue', '0004_recherche_publique'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduit',
            name='miniature',
            field=models.ImageField(blank=True, editable=False, help_text="WebP de 480 px de large au plus, généré depuis `image` (apps/catalogue/images.py). Vide si la génération a échoué : afficher l'original.", null=True, upload_to='catalogue/miniatures/%Y/%m/'),
        ),
        migrations.RunPython(
            executer(AVEC_MINIATURE),
            executer("DROP VIEW catalogue_produit_public", SANS_MINIATURE),
        ),
    ]
