# Generated by Django 6.0.7 on 2026-08-30 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("vendeurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasseportProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_passeport",
                    models.CharField(
                        db_index=True, editable=False, max_length=35, unique=True
                    ),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de série ou identifiant de lot de production",
                        max_length=60,
                    ),
                ),
                (
                    "origine_geographique",
                    models.CharField(
                        default="Côte d'Ivoire",
                        help_text="Région ou ville de fabrication (ex: Tiassalé, Grand-Bassam)",
                        max_length=150,
                    ),
                ),
                (
                    "materiaux_utilises",
                    models.TextField(
                        blank=True,
                        help_text="Composition détaillée (ex: Tissu Baoulé 100% coton, fil d'or, cuir véritable)",
                    ),
                ),
                ("date_fabrication", models.DateField(blank=True, null=True)),
                (
                    "artisan_createur",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'artisan ou de l'atelier de confection",
                        max_length=150,
                    ),
                ),
                (
                    "statut_certification",
                    models.CharField(
                        choices=[
                            ("certifie_authentique", "Certifié Authentique ANITCHE"),
                            ("label_local", "Fabriqué en Côte d'Ivoire"),
                            ("standard", "Standard"),
                        ],
                        default="certifie_authentique",
                        max_length=30,
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="passeports/qr/%Y/%m/"
                    ),
                ),
                (
                    "url_verification_publique",
                    models.URLField(blank=True, max_length=500),
                ),
                (
                    "nb_scans",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total de scans effectués par les consommateurs",
                    ),
                ),
                ("dernier_scan", models.DateTimeField(blank=True, null=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passeports",
                        to="vendeurs.boutique",
                        verbose_name="Boutique créatrice",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passeports",
                        to="catalogue.produit",
                        verbose_name="Produit associé",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passeports",
                        to="catalogue.varianteproduit",
                        verbose_name="Variante spécifique (optionnel)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passeport numérique produit",
                "verbose_name_plural": "Passeports numériques produits",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueScanPasseport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("date_scan", models.DateTimeField(auto_now_add=True)),
                (
                    "passeport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="passeport_qr.passeportproduit",
                        verbose_name="Passeport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de scan",
                "verbose_name_plural": "Historiques de scans",
                "ordering": ["-date_scan"],
            },
        ),
    ]
