# Generated by Django 6.0.8 on 2026-09-13 15:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passeport_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeportproduit',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='passeports/qr/%Y/%m/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
    ]
