# Generated by Django 6.0.8 on 2026-09-25 13:34

import ipaddress

from django.db import migrations, models
from django.db.models import Count


def verifier_absence_de_doublons(apps, schema_editor):
    """Arrêt explicite si des passeports existants violent « un passeport
    par lot ». Aucune fusion ni suppression automatique : choisir quel
    passeport conserver (lequel est déjà imprimé ?) est une décision
    métier. Corriger les ids listés puis relancer `migrate`."""
    PasseportProduit = apps.get_model('passeport_qr', 'PasseportProduit')
    doublons = (
        PasseportProduit.objects.exclude(numero_lot='')
        .values('produit', 'variante', 'numero_lot')
        .annotate(nb=Count('id')).filter(nb__gt=1)
    )
    problemes = []
    for doublon in doublons:
        ids = list(
            PasseportProduit.objects.filter(
                produit=doublon['produit'], variante=doublon['variante'], numero_lot=doublon['numero_lot'],
            ).values_list('code_passeport', flat=True)
        )
        problemes.append(
            f"produit={doublon['produit']}, variante={doublon['variante']}, "
            f"lot={doublon['numero_lot']!r} : {ids}"
        )
    if problemes:
        raise RuntimeError(
            "Passeports en double à corriger avant migration :\n- " + "\n- ".join(problemes)
        )


def tronquer_adresses_ip_existantes(apps, schema_editor):
    """Applique la minimisation (/24 IPv4, /48 IPv6) aux scans déjà journalisés.
    Logique recopiée de models.tronquer_adresse_ip : une migration ne doit
    pas dépendre du code applicatif, qui peut évoluer après elle."""
    HistoriqueScanPasseport = apps.get_model('passeport_qr', 'HistoriqueScanPasseport')
    for scan in HistoriqueScanPasseport.objects.exclude(adresse_ip__isnull=True).only('id', 'adresse_ip').iterator():
        adresse = ipaddress.ip_address(scan.adresse_ip)
        prefixe = 24 if adresse.version == 4 else 48
        reseau = str(ipaddress.ip_network(f"{adresse}/{prefixe}", strict=False).network_address)
        if reseau != scan.adresse_ip:
            HistoriqueScanPasseport.objects.filter(pk=scan.pk).update(adresse_ip=reseau)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_categorie_image_alter_imageproduit_image'),
        ('passeport_qr', '0002_alter_passeportproduit_qr_code_image'),
        ('vendeurs', '0004_boutique_nom_normalise'),
    ]

    operations = [
        migrations.RunPython(verifier_absence_de_doublons, migrations.RunPython.noop),
        migrations.RunPython(tronquer_adresses_ip_existantes, migrations.RunPython.noop),
        # Le QR est dessiné par le frontend à partir de l'URL de vérification.
        migrations.RemoveField(
            model_name='passeportproduit',
            name='qr_code_image',
        ),
        # Devenue une propriété calculée depuis settings.FRONTEND_BASE_URL.
        migrations.RemoveField(
            model_name='passeportproduit',
            name='url_verification_publique',
        ),
        migrations.AlterField(
            model_name='passeportproduit',
            name='statut_certification',
            field=models.CharField(choices=[('certifie_authentique', 'Certifié Authentique ANITCHE'), ('label_local', "Fabriqué en Côte d'Ivoire"), ('standard', 'Standard')], default='standard', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='passeportproduit',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_lot', ''), _negated=True), fields=('produit', 'variante', 'numero_lot'), name='passeport_unique_par_lot', nulls_distinct=False),
        ),
    ]
