# Generated by Django 6.0.8 on 2026-09-25 13:45

from django.db import migrations, models


def attribuer_les_desactivations_existantes(apps, schema_editor):
    """Passeports déjà inactifs : leur origine est inconnue (l'ancien code ne
    la notait pas). Choix prudent : administration. Un vendeur qui les avait
    désactivés lui-même devra demander leur réactivation ; l'inverse
    (attribuer au vendeur) lui rendrait la main sur une éventuelle
    révocation pour fraude."""
    PasseportProduit = apps.get_model('passeport_qr', 'PasseportProduit')
    PasseportProduit.objects.filter(est_actif=False).update(desactive_par='administration')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_categorie_image_alter_imageproduit_image'),
        ('passeport_qr', '0003_passeport_par_lot_sans_image_ni_url'),
        ('vendeurs', '0004_boutique_nom_normalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeportproduit',
            name='desactive_par',
            field=models.CharField(blank=True, choices=[('vendeur', 'Vendeur'), ('administration', 'Administration ANITCHE')], help_text="Qui a désactivé le passeport (vide s'il est actif). Une révocation de l'administration ne peut être levée que par elle.", max_length=20),
        ),
        migrations.RunPython(attribuer_les_desactivations_existantes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='passeportproduit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('desactive_par', ''), ('est_actif', True)), models.Q(('est_actif', False), models.Q(('desactive_par', ''), _negated=True)), _connector='OR'), name='passeport_desactivation_coherente'),
        ),
    ]
