# Generated by Django 6.0.8 on 2026-09-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_desactivation_et_regles_de_prix'),
        ('passeport_qr', '0005_certifications_vendeur_en_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeportproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passeports', to='catalogue.produit', verbose_name='Produit associé'),
        ),
        migrations.AlterField(
            model_name='passeportproduit',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passeports', to='catalogue.varianteproduit', verbose_name='Variante spécifique (optionnel)'),
        ),
    ]
