# Generated by Django 6.0.7 on 2026-08-30 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commandes", "0002_alter_commande_status"),
        ("vendeurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeRetour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_retour",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("produit_defectueux", "Produit défectueux ou endommagé"),
                            ("non_conforme", "Article non conforme à la description"),
                            ("mauvaise_taille", "Taille ou variante incorrecte"),
                            ("article_manquant", "Article manquant dans le colis"),
                            (
                                "changement_avis",
                                "Changement d'avis (droit de rétractation)",
                            ),
                            ("autre", "Autre motif"),
                        ],
                        default="produit_defectueux",
                        max_length=30,
                    ),
                ),
                (
                    "type_resolution",
                    models.CharField(
                        choices=[
                            ("remboursement", "Remboursement"),
                            ("echange", "Échange standard"),
                            ("avoir", "Avoir boutique"),
                        ],
                        default="remboursement",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demande", "Demande soumise"),
                            ("approuve", "Approuvée"),
                            ("rejete", "Rejetée"),
                            ("en_transit", "Colis retour en transit"),
                            ("receptionne", "Colis réceptionné"),
                            ("rembourse", "Remboursé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="demande",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Explications fournies par le client sur le problème rencontré"
                    ),
                ),
                (
                    "montant_remboursement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant total à rembourser calculé sur la base des articles retournés",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reponse_vendeur",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire ou motif de décision fourni par le vendeur/staff",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "boutique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_retour",
                        to="vendeurs.boutique",
                        verbose_name="Boutique concernée",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_retour",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retours",
                        to="commandes.commande",
                        verbose_name="Commande d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de retour",
                "verbose_name_plural": "Demandes de retour",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PhotoRetour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="retours/preuves/%Y/%m/")),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "demande_retour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="retours.demanderetour",
                        verbose_name="Demande de retour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo justificative de retour",
                "verbose_name_plural": "Photos justificatives de retour",
                "ordering": ["date_ajout"],
            },
        ),
        migrations.CreateModel(
            name="RetourItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "commande_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retours",
                        to="commandes.commandeitem",
                        verbose_name="Ligne de commande retournée",
                    ),
                ),
                (
                    "demande_retour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="retours.demanderetour",
                        verbose_name="Demande de retour parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article retourné",
                "verbose_name_plural": "Articles retournés",
            },
        ),
    ]
