# Generated by Django 6.0.8 on 2026-09-26 21:23

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retours', '0002_alter_photoretour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderetour',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demande soumise'), ('approuve', 'Approuvée'), ('rejete', 'Rejetée'), ('en_transit', 'Colis retour en transit'), ('receptionne', 'Colis réceptionné'), ('rembourse', 'Remboursé'), ('cloture', 'Clôturé'), ('annule', 'Annulée par le client')], db_index=True, default='demande', max_length=20),
        ),
        migrations.AlterField(
            model_name='photoretour',
            name='image',
            field=models.ImageField(upload_to=apps.core.storage.CheminUploadUUID('retours/preuves'), validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
    ]
