# Generated by Django 6.0.8 on 2026-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retours', '0003_statut_annule_photos_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderetour',
            name='frais_livraison_rembourses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
