# Generated by Django 6.0.7 on 2026-07-23 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('livreur', 'Livreur'), ('moderateur', 'Modérateur'), ('support', 'Service Client'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='client', max_length=20)),
                ('statut_kyc', models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='non_soumis', max_length=20)),
                ('email_verifie', models.BooleanField(default=False)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='DocumentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.FileField(upload_to='kyc/pieces_identite/')),
                ('selfie', models.ImageField(upload_to='kyc/selfies/')),
                ('numero_mobile_money', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('compte_bancaire', models.CharField(blank=True, max_length=50, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier KYC',
                'verbose_name_plural': 'Dossiers KYC',
            },
        ),
    ]
