# Generated by Django 6.0.7 on 2026-07-23 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('type_usage', models.CharField(choices=[('inscription', 'Inscription'), ('mdp_oublie', 'Mot de passe oublié'), ('changement_email', 'Changement email'), ('changement_telephone', 'Changement téléphone')], max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('nombre_tentatives', models.PositiveIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
            },
        ),
    ]
