# Generated by Django 6.0.7 on 2026-07-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_codeotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeotp',
            name='nouvelle_valeur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
