# Generated by Django 6.0.7 on 2026-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_codeotp_nouvelle_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='google_id',
            field=models.CharField(blank=True, help_text='Identifiant unique Google (sub), rempli si le compte est lié à Google.', max_length=255, null=True, unique=True),
        ),
    ]
