# Generated by Django 6.0.8 on 2026-09-13 15:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_utilisateur_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkyc',
            name='piece_identite',
            field=models.FileField(upload_to='kyc/pieces_identite/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.pdf'], taille_max_mo=10)]),
        ),
        migrations.AlterField(
            model_name='documentkyc',
            name='selfie',
            field=models.ImageField(upload_to='kyc/selfies/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
    ]
