# Generated by Django 6.0.8 on 2026-09-24 03:24

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_documentkyc_type_piece_recto_verso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkyc',
            name='piece_identite_recto',
            field=models.FileField(upload_to=apps.core.storage.CheminUploadUUID('kyc/pieces_identite/recto'), validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.pdf'], taille_max_mo=10)]),
        ),
        migrations.AlterField(
            model_name='documentkyc',
            name='piece_identite_verso',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.storage.CheminUploadUUID('kyc/pieces_identite/verso'), validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.pdf'], taille_max_mo=10)]),
        ),
        migrations.AlterField(
            model_name='documentkyc',
            name='selfie',
            field=models.ImageField(upload_to=apps.core.storage.CheminUploadUUID('kyc/selfies'), validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.webp'], taille_max_mo=5)]),
        ),
    ]
