# Generated by Django 6.0.8 on 2026-09-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_chiffrement_donnees_financieres_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentkyc',
            name='compte_bancaire',
        ),
    ]
