/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recherche/produits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recherche, filtres, tri et facettes des produits visibles
         * @description Produits visibles dans Django (vue catalogue_produit_public), 20 par
         *     page. Facettes (catégories, boutiques, prix) sur tout l'ensemble filtré,
         *     en page 1 ; total et facettes en cache 60 s, résultats jamais.
         */
        get: operations["rechercher_produits_recherche_produits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recherche/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplétion : catégories, boutiques et produits visibles
         * @description Catégories actives et boutiques publiques (2 au plus chacune), puis
         *     produits visibles. Sans accents ; tolère une faute de frappe. En cache
         *     60 s.
         */
        get: operations["obtenir_suggestions_recherche_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ia/conseil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conseil argumenté et produits du catalogue
         * @description Produits visibles et en stock choisis dans le catalogue selon la
         *     conversation (tenue par le frontend), l'occasion, le style, le budget
         *     et les catégories, avec une justification par produit.
         */
        post: operations["conseiller_shopping_ia_conseil_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ia/recommandations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sélection selon les catégories et le budget
         * @description Produits visibles et en stock des catégories demandées (tout le
         *     catalogue sans catégorie), au plus au prix du budget.
         */
        post: operations["obtenir_recommandations_ia_recommandations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qr/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Décoder un QR ou un code passeport saisi (sans le certifier)
         * @description Code saisi (espaces, tirets et casse tolérés) ou URL de vérification
         *     de FRONTEND_BASE_URL. Un 200 ne dit pas que le passeport existe :
         *     ouvrir `url_verification_publique`, dont la page appelle Django.
         */
        post: operations["scanner_qr_qr_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livraison/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publier la position du livreur assigné (livraison en cours)
         * @description Le livreur est l'utilisateur du jeton, l'horodatage celui du serveur.
         *     Rythme conseillé : une position toutes les 5 s ; arrêt sur 403, 404, 409.
         *
         *     Refus (`errors.code`) : 403 `acces_reserve_livreurs`, 403
         *     `livraison_non_assignee`, 404 `livraison_introuvable`, 409
         *     `livraison_pas_en_cours`.
         */
        post: operations["publier_position_livraison_position_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livraison/position/{livraison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dernière position du livreur (livraison en cours)
         * @description 404 `livraison_introuvable` : hors périmètre ou inexistante (comme
         *     Django). 404 `aucune_position` : pas en cours, jamais publiée, expirée ou
         *     publiée par un ancien livreur ; rien à afficher, ce n'est pas une panne.
         *     Jamais de position par défaut.
         */
        get: operations["obtenir_position_livraison_position__livraison_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * État du service
         * @description État de PostgreSQL et de Redis, sans version ni détail technique.
         *     200 si tout répond, 503 sinon (healthcheck Docker, nginx).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Page d'accueil de l'API FastAPI.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DemandeConseil */
        DemandeConseil: {
            /**
             * Messages
             * @description Historique tenu par le frontend, 10 messages au plus, le dernier du client
             */
            messages: components["schemas"]["MessageChat"][];
            /**
             * Occasion
             * @description Occasion libre (mariage, cadeau…), 60 caractères au plus
             */
            occasion?: string | null;
            /**
             * Style
             * @description Style libre (traditionnel, wax…), 60 caractères au plus
             */
            style?: string | null;
            /**
             * Budget Max
             * @description Budget maximum en FCFA entiers (prix affiché)
             */
            budget_max?: number | null;
            /**
             * Categories
             * @description Slugs ou ids de catégorie (sous-catégories comprises), comme `categorie` de la recherche
             */
            categories?: string[];
        };
        /** DemandeRecommandations */
        DemandeRecommandations: {
            /**
             * Categories
             * @description Slugs ou ids de catégorie ; vide : tout le catalogue
             */
            categories?: string[];
            /**
             * Budget Max
             * @description Budget maximum en FCFA entiers (prix affiché)
             */
            budget_max?: number | null;
        };
        /** DemandeScanQR */
        DemandeScanQR: {
            /**
             * Qr Data
             * @description Contenu brut lu dans le QR (URL de vérification) ou code saisi à la main. 1 à 512 caractères, espaces de début et de fin retirés.
             * @example https://anitche.com/qr/verifier/PAS-2026-1A2B3C4D
             * @example PAS 2026 1a2b3c4d
             */
            qr_data: string;
        };
        /**
         * Error
         * @description Schéma OpenAPI « Error » : toutes les réponses d'erreur.
         */
        Error: {
            /**
             * Success
             * @default false
             */
            success: boolean;
            /** Status Code */
            status_code: number;
            /** Detail */
            detail: string;
            /**
             * Errors
             * @default {}
             */
            errors: {
                [key: string]: string[];
            };
        };
        /** FacetteBoutique */
        FacetteBoutique: {
            /** Id */
            id: number;
            /** Nom */
            nom: string;
            /** Slug */
            slug: string;
            /** Nombre */
            nombre: number;
        };
        /** FacetteCategorie */
        FacetteCategorie: {
            /** Id */
            id: number;
            /** Nom */
            nom: string;
            /** Slug */
            slug: string;
            /**
             * Parent
             * @description Catégorie parente, null pour une catégorie racine
             */
            parent: number | null;
            /** Nombre */
            nombre: number;
        };
        /** FacettePrix */
        FacettePrix: {
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /**
             * Tranches
             * @description Tranches non vides seulement
             */
            tranches: components["schemas"]["TranchePrix"][];
        };
        /** FacettesRecherche */
        FacettesRecherche: {
            /**
             * Categories
             * @description Catégories directes des résultats (20 au plus)
             */
            categories: components["schemas"]["FacetteCategorie"][];
            /**
             * Boutiques
             * @description Boutiques des résultats (10 au plus)
             */
            boutiques: components["schemas"]["FacetteBoutique"][];
            prix: components["schemas"]["FacettePrix"];
        };
        /** MessageChat */
        MessageChat: {
            /**
             * Role
             * @description « user » : le client ; « assistant » : une réponse précédente du conseiller, renvoyée telle quelle par le frontend (historique)
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * Contenu
             * @description 1 à 1000 caractères après fusion des espaces
             */
            contenu: string;
        };
        /**
         * PositionLivreur
         * @description Position montrée au client et à l'administration (jamais l'identifiant
         *     du livreur). Distance et temps : estimation indicative, null si le
         *     client n'a pas donné son point GPS au checkout.
         */
        PositionLivreur: {
            /**
             * Livraison Id
             * Format: uuid
             */
            livraison_id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Vitesse Kmh */
            vitesse_kmh: number | null;
            /** Cap Degres */
            cap_degres: number | null;
            /**
             * Horodatage
             * @description Heure du serveur à la réception, UTC, ISO 8601 (« …Z »).
             */
            horodatage: string;
            /**
             * Distance Restante Km
             * @description Indicative : vol d'oiseau × facteur de détour. null sans point GPS du client.
             */
            distance_restante_km: number | null;
            /**
             * Temps Estime Minutes
             * @description Indicatif : vitesse moyenne urbaine, sans trafic. null sans point GPS du client.
             */
            temps_estime_minutes: number | null;
        };
        /**
         * PositionPublication
         * @description Corps de POST /livraison/position.
         *
         *     Le livreur est l'utilisateur du jeton et l'horodatage est celui du
         *     serveur : `livreur_id` et `horodatage` envoyés par un client sont
         *     ignorés, comme tout champ inconnu.
         */
        PositionPublication: {
            /**
             * Livraison Id
             * Format: uuid
             */
            livraison_id: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Vitesse Kmh */
            vitesse_kmh?: number | null;
            /** Cap Degres */
            cap_degres?: number | null;
        };
        /** ProduitConseille */
        ProduitConseille: {
            /** Id */
            id: number;
            /** Nom */
            nom: string;
            /** Slug */
            slug: string;
            /**
             * Prix Base
             * @description Prix de base en FCFA, chaîne à 2 décimales (« 4500.00 »), comme Django
             */
            prix_base: string;
            /**
             * Prix Min
             * @description Prix affiché : plus petit prix effectif (promo comprise) des variantes actives
             */
            prix_min: number;
            /**
             * Image Principale
             * @description URL absolue de l'image principale, ou null
             */
            image_principale: string | null;
            /**
             * Miniature Principale
             * @description URL absolue de la miniature WebP (480 px de large au plus) de la même image que `image_principale`, ou null (pas encore générée) : afficher alors `image_principale`
             */
            miniature_principale: string | null;
            /** Categorie */
            categorie: number | null;
            /**
             * Categorie Nom
             * @description null si le produit n'a pas de catégorie (Django omet alors la clé)
             */
            categorie_nom: string | null;
            /** Boutique */
            boutique: number;
            /** Boutique Nom */
            boutique_nom: string;
            /** Boutique Slug */
            boutique_slug: string;
            /**
             * En Stock
             * @description Au moins une variante active en stock (jamais la quantité)
             */
            en_stock: boolean;
            /**
             * Date Creation
             * @description ISO 8601, UTC (« …Z »)
             */
            date_creation: string;
            /**
             * Justification
             * @description Pourquoi ce produit (300 caractères au plus, texte brut)
             */
            justification: string;
        };
        /**
         * ProduitRecherche
         * @description Mêmes champs que ProduitPublicListSerializer (Django).
         */
        ProduitRecherche: {
            /** Id */
            id: number;
            /** Nom */
            nom: string;
            /** Slug */
            slug: string;
            /**
             * Prix Base
             * @description Prix de base en FCFA, chaîne à 2 décimales (« 4500.00 »), comme Django
             */
            prix_base: string;
            /**
             * Prix Min
             * @description Prix affiché : plus petit prix effectif (promo comprise) des variantes actives
             */
            prix_min: number;
            /**
             * Image Principale
             * @description URL absolue de l'image principale, ou null
             */
            image_principale: string | null;
            /**
             * Miniature Principale
             * @description URL absolue de la miniature WebP (480 px de large au plus) de la même image que `image_principale`, ou null (pas encore générée) : afficher alors `image_principale`
             */
            miniature_principale: string | null;
            /** Categorie */
            categorie: number | null;
            /**
             * Categorie Nom
             * @description null si le produit n'a pas de catégorie (Django omet alors la clé)
             */
            categorie_nom: string | null;
            /** Boutique */
            boutique: number;
            /** Boutique Nom */
            boutique_nom: string;
            /** Boutique Slug */
            boutique_slug: string;
            /**
             * En Stock
             * @description Au moins une variante active en stock (jamais la quantité)
             */
            en_stock: boolean;
            /**
             * Date Creation
             * @description ISO 8601, UTC (« …Z »)
             */
            date_creation: string;
        };
        /** ReponseConseil */
        ReponseConseil: {
            /**
             * Reponse
             * @description Message du conseiller (texte brut, 600 caractères au plus)
             */
            reponse: string;
            /**
             * Produits Suggeres
             * @description 4 au plus, produits visibles et en stock
             */
            produits_suggeres: components["schemas"]["ProduitConseille"][];
            /**
             * Conseils Style
             * @description 3 au plus
             */
            conseils_style: string[];
            /**
             * Source
             * @description « regles » : sélection par règles (simulé ou repli) ; « ia » : fournisseur d'IA
             * @enum {string}
             */
            source: "regles" | "ia";
        };
        /** ReponseRecherche */
        ReponseRecherche: {
            /**
             * Count
             * @description Total des résultats (peut avoir 60 s de retard : cache)
             */
            count: number;
            /** Next */
            next: string | null;
            /** Previous */
            previous: string | null;
            /** Results */
            results: components["schemas"]["ProduitRecherche"][];
            /** @description Calculées sur tout l'ensemble filtré, en page 1 seulement */
            facettes: components["schemas"]["FacettesRecherche"] | null;
        };
        /** ReponseRecommandations */
        ReponseRecommandations: {
            /**
             * Recommandations
             * @description 8 au plus, produits visibles et en stock
             */
            recommandations: components["schemas"]["ProduitConseille"][];
            /**
             * Source
             * @enum {string}
             */
            source: "regles" | "ia";
        };
        /** ReponseScanQR */
        ReponseScanQR: {
            /**
             * Code Passeport
             * @description Code normalisé PAS-AAAA-XXXXXXXX. N'atteste PAS que le passeport existe : la page de vérification appelle Django, qui certifie.
             * @example PAS-2026-1A2B3C4D
             */
            code_passeport: string;
            /**
             * Url Verification Publique
             * @description Page de vérification du frontend : FRONTEND_BASE_URL + /qr/verifier/ + code, même valeur que le champ de Django.
             * @example https://anitche.com/qr/verifier/PAS-2026-1A2B3C4D
             */
            url_verification_publique: string;
        };
        /** ReponseSuggestions */
        ReponseSuggestions: {
            /** Requete */
            requete: string;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** Suggestion */
        Suggestion: {
            /**
             * Type
             * @enum {string}
             */
            type: "categorie" | "boutique" | "produit";
            /** Texte */
            texte: string;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
        };
        /** TranchePrix */
        TranchePrix: {
            /**
             * Min
             * @description Borne basse incluse (FCFA)
             */
            min: number;
            /**
             * Max
             * @description Borne haute exclue (FCFA), null pour la dernière tranche
             */
            max: number | null;
            /** Nombre */
            nombre: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rechercher_produits_recherche_produits_get: {
        parameters: {
            query?: {
                /** @description pertinence (défaut avec recherche), date_desc (défaut sans), date_asc, prix_asc, prix_desc */
                tri?: ("pertinence" | "prix_asc" | "prix_desc" | "date_desc" | "date_asc") | null;
                /** @description Page de 20 résultats, 50 au plus */
                page?: number;
                /** @description Texte cherché, 2 à 100 caractères, sans tenir compte des accents ni des majuscules. Cherché dans le nom et la description des produits, et dans les noms de boutique et de catégorie. */
                recherche?: string | null;
                /** @description Slug ou id de catégorie, sous-catégories comprises */
                categorie?: string | null;
                /** @description Id (chiffres uniquement) ou slug de boutique */
                boutique?: string | null;
                /** @description Prix affiché minimum, FCFA entiers */
                prix_min?: number | null;
                /** @description Prix affiché maximum, FCFA entiers */
                prix_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseRecherche"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenir_suggestions_recherche_suggestions_get: {
        parameters: {
            query: {
                /** @description Début du texte saisi, 3 à 50 caractères */
                recherche: string;
                /** @description Nombre de suggestions, 10 au plus */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseSuggestions"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    conseiller_shopping_ia_conseil_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeConseil"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseConseil"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `errors.code` : `conseiller_desactive` (conseiller coupé : masquer l'entrée) ou `conseiller_indisponible` (catalogue injoignable : réessayer plus tard). Sans code : Redis ou vérification du jeton indisponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenir_recommandations_ia_recommandations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeRecommandations"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseRecommandations"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `errors.code` : `conseiller_desactive` (conseiller coupé : masquer l'entrée) ou `conseiller_indisponible` (catalogue injoignable : réessayer plus tard). Sans code : Redis ou vérification du jeton indisponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    scanner_qr_qr_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandeScanQR"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReponseScanQR"];
                };
            };
            /** @description Contenu refusé, errors.code : code_passeport_invalide (ni code ni URL), qr_non_anitche (autre site ou URL piégée : ne jamais l'ouvrir), lien_non_passeport (page ANITCHE qui n'est pas un passeport). Corps invalide : errors.qr_data. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    publier_position_livraison_position_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionPublication"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionLivreur"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La livraison n'est pas en cours (errors.code : livraison_pas_en_cours). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenir_position_livraison_position__livraison_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                livraison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionLivreur"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
