# Generated by Django 6.0.7 on 2026-08-22 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panieritem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='catalogue.varianteproduit', verbose_name='Variante de produit'),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
