# Generated by Django 6.0.7 on 2026-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('creee', 'Créée'), ('confirmee', 'Confirmée'), ('preparation', 'Préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='creee', max_length=20),
        ),
    ]
