# Generated by Django 6.0.8 on 2026-09-26 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commandeitem_variante'),
        ('vendeurs', '0004_boutique_nom_normalise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.CharField(blank=True, choices=[('client', 'Annulée par le client'), ('expiration', 'Non payée dans le délai'), ('administration', "Annulée par l'administration"), ('boutique_indisponible', 'Boutique indisponible')], max_length=30),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_point_de_repere',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_quartier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendeurs.boutique'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
