# Generated by Django 6.0.8 on 2026-09-26 18:00

from django.db import migrations, models
from django.db.models import F


def ventes_passees_sans_frais(apps, schema_editor):
    """Articles vendus avant les frais vendeur : aucun frais n'était convenu,
    le net vendeur est le prix de la ligne (jamais recalculé avec un barème)."""
    CommandeItem = apps.get_model("commandes", "CommandeItem")
    CommandeItem.objects.update(montant_net_vendeur=F("prix_unitaire") * F("quantite"))


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_adresse_livraison_annulation_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeitem',
            name='frais_fixe_unitaire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='montant_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='montant_frais_fixes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='montant_net_vendeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.RunPython(ventes_passees_sans_frais, migrations.RunPython.noop),
    ]
