# Generated by Django 6.0.8 on 2026-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_frais_vendeur_figes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='motif_annulation',
            field=models.CharField(blank=True, choices=[('client', 'Annulée par le client'), ('expiration', 'Non payée dans le délai'), ('administration', "Annulée par l'administration"), ('boutique_indisponible', 'Boutique indisponible'), ('livraison_echouee', 'Livraison échouée')], max_length=30),
        ),
    ]
