# Generated by Django 6.0.8 on 2026-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_motif_livraison_echouee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison_vendeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commande',
            name='livraison_offerte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_zone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
