# Generated by Django 6.0.8 on 2026-09-27 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_frais_de_livraison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='groupecommande',
            name='livraison_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='groupecommande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('livraison_latitude__isnull', True), ('livraison_longitude__isnull', True)), models.Q(('livraison_latitude__isnull', False), ('livraison_longitude__isnull', False)), _connector='OR'), name='groupe_commande_position_complete_ou_absente'),
        ),
    ]
