# Generated by Django 6.0.7 on 2026-07-25 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0003_codeotp_nouvelle_valeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeVendeur',
            fields=[
            ],
            options={
                'verbose_name': 'Demande vendeur',
                'verbose_name_plural': 'Demandes vendeur (en attente)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='boutiques/bannieres/')),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('est_active', models.BooleanField(default=True, help_text='Décochez pour fermer temporairement la boutique (elle disparaît du catalogue public).')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['nom'],
            },
        ),
    ]
