# Generated by Django 6.0.8 on 2026-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeurs', '0002_alter_boutique_banniere_alter_boutique_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='est_suspendue',
            field=models.BooleanField(default=False, help_text="Suspension par l'administration : la boutique disparaît du catalogue public et le vendeur ne peut pas la lever lui-même."),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='est_active',
            field=models.BooleanField(default=True, help_text='Fermeture volontaire par le vendeur (la boutique disparaît du catalogue public).'),
        ),
    ]
