# Generated by Django 6.0.8 on 2026-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeurs', '0004_boutique_nom_normalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='livraison_offerte',
            field=models.BooleanField(default=False, help_text='Livraison offerte au client : les frais sont déduits du reversement du vendeur.'),
        ),
    ]
