# Generated by Django 6.0.7 on 2026-08-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_status'),
        ('support', '0002_supportticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='commandes.commande'),
        ),
    ]
