# Generated by Django 6.0.8 on 2026-09-13 15:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='support/attachments/%Y/%m/', validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.pdf'], taille_max_mo=10)]),
        ),
    ]
