# Generated by Django 6.0.8 on 2026-09-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_desactivation_et_regles_de_prix'),
        ('support', '0004_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='catalogue.produit'),
        ),
    ]
