# Generated by Django 6.0.8 on 2026-09-26 22:23

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_produit_protege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.storage.CheminUploadUUID('support/pieces_jointes'), validators=[apps.core.validators.ValidateurFichierSecurise(extensions=['.jpg', '.jpeg', '.png', '.pdf'], taille_max_mo=10)]),
        ),
    ]
