# Generated by Django 6.0.7 on 2026-08-30 00:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteFidelite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "solde_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Points actuellement disponibles pour échange",
                    ),
                ),
                (
                    "points_cumules_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total des points acquis depuis l'inscription",
                    ),
                ),
                (
                    "palier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze (0 - 499 pts)"),
                            ("argent", "Argent (500 - 1999 pts)"),
                            ("or", "Or (2000 - 4999 pts)"),
                            ("platine", "Platine (5000+ pts)"),
                        ],
                        db_index=True,
                        default="bronze",
                        max_length=15,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compte_fidelite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de fidélité",
                "verbose_name_plural": "Comptes de fidélité",
            },
        ),
        migrations.CreateModel(
            name="CouponReduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "type_reduction",
                    models.CharField(
                        choices=[
                            ("pourcentage", "Pourcentage (%)"),
                            ("montant_fixe", "Montant fixe (FCFA)"),
                        ],
                        default="pourcentage",
                        max_length=20,
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valeur de la réduction (ex: 10 pour 10% ou 2000 pour 2000 FCFA)",
                        max_digits=10,
                    ),
                ),
                (
                    "montant_minimum_commande",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant minimum d'achat requis en FCFA",
                        max_digits=12,
                    ),
                ),
                (
                    "points_requis",
                    models.PositiveIntegerField(
                        default=0, help_text="Points consommés pour obtenir ce coupon"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("est_utilise", models.BooleanField(default=False)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client bénéficiaire (optionnel si public)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon de réduction",
                "verbose_name_plural": "Coupons de réduction",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TransactionFidelite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[
                            ("gain", "Gain sur achat"),
                            ("depense", "Conversion en bon de réduction"),
                            ("expiration", "Points expirés"),
                            ("parrainage", "Bonus de parrainage"),
                            ("ajustement", "Ajustement administratif"),
                        ],
                        default="gain",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Nombre de points (positif pour gain, négatif pour dépense)"
                    ),
                ),
                (
                    "solde_apres",
                    models.PositiveIntegerField(
                        help_text="Solde de points après l'opération"
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("reference_externe", models.CharField(blank=True, max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="fidelite.comptefidelite",
                        verbose_name="Compte de fidélité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de fidélité",
                "verbose_name_plural": "Transactions de fidélité",
                "ordering": ["-date_creation"],
            },
        ),
    ]
