# Generated by Django 6.0.8 on 2026-09-26 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_motif_livraison_echouee'),
        ('fidelite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GainFidelite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('credite', 'Crédité'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=15)),
                ('date_disponibilite', models.DateTimeField(db_index=True)),
                ('motif_annulation', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gain de fidélité',
                'verbose_name_plural': 'Gains de fidélité',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
            },
        ),
        migrations.AddField(
            model_name='couponreduction',
            name='nombre_utilisations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponreduction',
            name='utilisations_max',
            field=models.PositiveIntegerField(blank=True, default=1, help_text="Nombre total d'utilisations autorisées (vide = illimité). Chaque client ne l'utilise qu'une fois.", null=True),
        ),
        migrations.AlterField(
            model_name='transactionfidelite',
            name='type_transaction',
            field=models.CharField(choices=[('gain', 'Gain sur achat'), ('depense', 'Conversion en bon de réduction'), ('expiration', 'Points expirés'), ('parrainage', 'Bonus de parrainage'), ('ajustement', 'Ajustement administratif'), ('reprise', 'Reprise (achat remboursé)')], default='gain', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='couponreduction',
            constraint=models.CheckConstraint(condition=models.Q(('valeur__gt', 0)), name='coupon_valeur_positive'),
        ),
        migrations.AddConstraint(
            model_name='couponreduction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_reduction', 'pourcentage'), _negated=True), ('valeur__lte', 100), _connector='OR'), name='coupon_pourcentage_au_plus_100'),
        ),
        migrations.AddConstraint(
            model_name='couponreduction',
            constraint=models.CheckConstraint(condition=models.Q(('montant_minimum_commande__gte', 0)), name='coupon_minimum_positif'),
        ),
        migrations.AddConstraint(
            model_name='transactionfidelite',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_externe', ''), _negated=True), fields=('compte', 'type_transaction', 'reference_externe'), name='transaction_fidelite_unique_par_reference'),
        ),
        migrations.AddField(
            model_name='gainfidelite',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gain_fidelite', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='gainfidelite',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='fidelite.comptefidelite'),
        ),
        migrations.AddField(
            model_name='utilisationcoupon',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_coupon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisationcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='fidelite.couponreduction'),
        ),
        migrations.AddField(
            model_name='utilisationcoupon',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations_coupon', to='commandes.groupecommande'),
        ),
        migrations.AddConstraint(
            model_name='utilisationcoupon',
            constraint=models.UniqueConstraint(fields=('coupon', 'client'), name='coupon_une_utilisation_par_client'),
        ),
    ]
