# Generated by Django 6.0.7 on 2026-08-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalogue/categories/')),
                ('est_active', models.BooleanField(default=True, help_text='Décochez pour masquer la catégorie et ses sous-catégories du catalogue public.')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (du plus petit au plus grand).")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='catalogue.categorie', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_base', models.DecimalField(decimal_places=2, default=0, help_text='Prix de base ou prix indicatif en FCFA', max_digits=12)),
                ('est_actif', models.BooleanField(default=True, help_text='Décochez pour retirer le produit du catalogue public.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='vendeurs.boutique', verbose_name='Boutique')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/produits/%Y/%m/')),
                ('est_principale', models.BooleanField(default=False, help_text='Image principale affichée sur les vignettes de recherche.')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produits',
                'ordering': ['ordre', '-est_principale', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Code SKU unique de gestion des stocks', max_length=64, unique=True)),
                ('nom', models.CharField(help_text='Ex : Taille M / Rouge, ou Modèle standard', max_length=150)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix de vente standard en FCFA', max_digits=12)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, help_text='Prix promotionnel optionnel en FCFA', max_digits=12, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Poids unitaire en kg (utile pour le calcul des frais de livraison)', max_digits=6, null=True)),
                ('est_active', models.BooleanField(default=True, help_text='Désactiver cette déclinaison sans toucher aux autres')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variante produit',
                'verbose_name_plural': 'Variantes produits',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.PositiveIntegerField(default=0, help_text="Nombre d'unités physiques disponibles à la vente")),
                ('seuil_alerte', models.PositiveIntegerField(default=5, help_text='Seuil à partir duquel une notification de stock faible est émise')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('variante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalogue.varianteproduit', verbose_name='Variante de produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
