# Generated by Django 6.0.7 on 2026-08-30 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("commande", "Commande"),
                            ("paiement", "Paiement"),
                            ("livraison", "Livraison"),
                            ("kyc", "Vérification KYC"),
                            ("stock", "Alerte de Stock"),
                            ("support", "Support Client"),
                            ("systeme", "Système"),
                        ],
                        db_index=True,
                        default="systeme",
                        max_length=20,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                        ],
                        default="in_app",
                        max_length=15,
                    ),
                ),
                ("est_lu", models.BooleanField(db_index=True, default=False)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "lien_redirection",
                    models.CharField(
                        blank=True,
                        help_text="URL relative ou deep-link vers la ressource associée (ex: /commandes/CMD-2026-X)",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données contextuelles additionnelles (IDs techniques, totaux, etc.)",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PreferenceNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir les notifications importantes par email",
                    ),
                ),
                (
                    "sms_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir les notifications urgentes et OTP par SMS",
                    ),
                ),
                (
                    "in_app_actif",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir les alertes dans le centre de notifications in-app",
                    ),
                ),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_notification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
    ]
