# Generated by Django 6.0.8 on 2026-09-26 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencenotification',
            name='in_app_actif',
        ),
        migrations.RemoveField(
            model_name='preferencenotification',
            name='sms_actif',
        ),
        migrations.AlterField(
            model_name='preferencenotification',
            name='email_actif',
            field=models.BooleanField(default=True, help_text='Recevoir les notifications par email (hors emails indispensables : code de livraison, sécurité du compte)'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', '-date_creation'], name='notif_destinataire_date'),
        ),
    ]
