# Generated by Django 6.0.8 on 2026-10-06 11:54

from django.db import migrations, models
from django.db.models import Value
from django.db.models.functions import Concat, Left, Substr

ANCIEN_PREFIXE = "/admin/"
NOUVEAU_PREFIXE = "/administration/"
LONGUEUR_MAX = 255


def _remplacer_prefixe(apps, ancien, nouveau):
    """Un seul UPDATE : chaque lien qui commence par `ancien` le voit
    remplacé par `nouveau` (le reste du chemin est conservé)."""
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(lien_redirection__startswith=ancien).update(
        lien_redirection=Left(
            Concat(Value(nouveau), Substr("lien_redirection", len(ancien) + 1)), LONGUEUR_MAX,
        ),
    )


def vers_administration(apps, schema_editor):
    _remplacer_prefixe(apps, ANCIEN_PREFIXE, NOUVEAU_PREFIXE)


def vers_admin(apps, schema_editor):
    _remplacer_prefixe(apps, NOUVEAU_PREFIXE, ANCIEN_PREFIXE)


class Migration(migrations.Migration):
    """Liens de notification de l'administration : `/admin/…` (qui, suivi
    tel quel, mène à l'admin Django) devient `/administration/…`, comme les
    liens produits par apps/notifications/liens.py. Retour arrière : le
    préfixe `/administration/` redevient `/admin/`."""

    dependencies = [
        ('notifications', '0002_preference_email_seule_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='lien_redirection',
            field=models.CharField(blank=True, help_text='Route logique de la ressource, à associer à une page par chaque portail : un chemin (jamais une URL, ni un hôte, ni une requête), ou vide si la notification ne mène nulle part. Liste fermée (apps/notifications/liens.py) : /commandes, /commandes/{uuid}, /livraisons/{uuid}, /retours/{uuid}, /paiements/{uuid}, /fidelite/mon-compte, /support/tickets/{uuid}, /vendeur/commandes/{uuid}, /vendeur/produits/{id}, /vendeur/retours/{uuid}, /vendeur/reversements, /administration/retours/{uuid}, /administration/remboursements, /administration/livraisons/{uuid}. Un préfixe inconnu mène au centre de notifications.', max_length=255),
        ),
        migrations.RunPython(vers_administration, vers_admin),
    ]
